on:
  push:
    branches: [ master ]
    tags-ignore: 
        - '*'
    
jobs:
 version-bump:
  runs-on: ubuntu-latest
   
  steps:
     - name: Checkout
       uses: actions/checkout@v2
       with:
         token: ${{ secrets.SECRET_TOKEN }}
       
     - name: Set github token
       uses: fregante/setup-git-token@v1
       with:
        token: ${{ secrets.GITHUB_TOKEN }}
       
     - name: Push New Tag
       run: |
            
            #git fetch 
            git fetch -a
            
            #checkout master
            git checkout master
            
            #git pull
            git pull origin
           
            #get the latest tag from git
            tag=$(echo "$(git describe --abbrev=0 --tags)")
            echo tag: $tag

            current_version=$tag

            #take the last version from tag ex: 6.5
            version=$(echo "${current_version##*-v}")
            echo version: $version

            #increment the version by 0.1
            new_version=$(echo $version 0.1 | awk '{printf "%.1f", $1 + $2}')
            echo new_version: $new_version

            # new version with current date
            release_tag=$(echo "R-ATV-$(date -d "+330 min" +"%d.%m.%y")-v$new_version")
            echo release_tag: $release_tag
            
            #push new tag to git
            git tag -a  $release_tag -m " "
        
            

