on: 
 push:
  branches:
    - [ master ]
  tags-ignore:
    - '*'
    
jobs:
  runs-on:
   - ubuntu-latest
   
  steps:
     - name: Push New Tag
     - run: |
            #get the latest tag from git
            tag=$(echo "$(git describe --abbrev=0)")

            current_version=$tag

            #take the last 3 digits of the tag ex: 6.5
            version=$(echo "${current_version: -3}")

            #increment the version by 0.1
            new_version=$(echo $version 0.1 | awk '{printf "%.1f", $1 + $2}')
            echo $new_version

            #form new version with current date
            updated_version=$(echo "R-ATV-$(date -d "+330 min" +"%d.%m.%y")-v$new_version")
            echo $updated_version
            
            #push new tag to git
            git tag -a  $updated_version

