on:
  push:
    branches: [ master ]
    tags-ignore: 
        - '*'
    
jobs:
 create-release-tag:
  runs-on: ubuntu-latest
   
  steps:
     - name: Checkout
       uses: actions/checkout@v2
       with:
         token: ${{ secrets.SECRET_TOKEN }}
       
     - name: Set github token
       uses: fregante/setup-git-token@v1
       with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
     - name: Git fetch 
       run:  git fetch -a
    
     - name: Checkout master
       run:  git checkout master
       
     - name: Git pull
       run:  git pull origin
       
     - name: Get the latest tag from git
       id:  "step1"
       run: |
            echo "::set-output name=tag::$(git describe --tags $(git rev-list --tags --max-count=1))"
            echo git_tag: $(git describe --tags $(git rev-list --tags --max-count=1))
       
     - name: Take the last version from tag
       id:  "step2"
       env: 
          TAG: ${{ steps.step1.outputs.tag }}
       run: |
            echo "::set-output name=version::$(echo "${$TAG#*-v}")" #extract version number from the latest tag ex: 6.5 
            echo tag: ${{ steps.step1.outputs.tag }}
       
     - name: Increment version
       id:  "step3"
       run: |
            echo "::set-output name=new_version::$(echo ${{ steps.step2.outputs.version }} 0.1 | awk '{printf "%.1f", $1 + $2}')"  #6.5 + 0.1 =  "6.6"
            echo version:${{ steps.step2.outputs.version }} 
            
     - name: Generate new tag with current date
       id:  "step4"
       run: |
            echo "::set-output name=release_tag::$(echo "R-ATV-$(date -d "+330 min" +"%d.%m.%y")-v${{ steps.step3.outputs.new_version }}")"
            echo new_version:${{ steps.step3.outputs.new_version }}
            
     - name: Add new tag
       run:  git tag -a  ${{ steps.step4.outputs.release_tag }} -m "Release tag" 
             echo release_tag:${{ steps.step4.outputs.release_tag }}
                    
     - name: Push new tag
       run:  git push origin
