on:
  push:
    branches: [ master ]
    tags-ignore: 
        - '*'
    
jobs:
 create-release-tag:
  runs-on: ubuntu-latest
   
  steps:
     - name: Checkout
       uses: actions/checkout@v2
       with:
         token: ${{ secrets.SECRET_TOKEN }}
       
     - name: Set github token
       uses: fregante/setup-git-token@v1
       with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
     - name: Git fetch 
       run:  git fetch -a
    
     - name: Checkout master
       run:  git checkout master
       
     - name: Git pull
       run:  git pull origin
       
     - name: Get the latest tag from git
       id:  "tags"
       run: |
            echo "::set-output name=tag::$(git describe --tags $(git rev-list --tags --max-count=1))"
            echo server_tags: ${{ steps.tags.outputs.tag }}
       
     - name: Take the last version from tag
       id:  "versions"
       run: |
            echo "::set-output name=version::$(echo "${"${{ steps.tags.outputs.tag }}"##*-v}")" #extract version number from the latest tag ex: 6.5 
            echo version:v${{ steps.versions.output.version }}
       
     - name: Increment version
       id:  "generate_new_version"
       run: |
            echo "::set-output name=new_version::$(echo ${{ steps.versions.outputs.version }} 0.1 | awk '{printf "%.1f", $1 + $2}')"  #6.5 + 0.1 =  "6.6"
            echo new_version:${{ steps.generate_new_version.output.new_version }}
            
     - name: Generate new tag with current date
       id:  "generate_new_tag"
       run: |
            echo "::set-output name=release_tag::$(echo "R-ATV-$(date -d "+330 min" +"%d.%m.%y")-v${{ steps.generate_new_version.output.new_version }}")"
            echo release_tag:${{ steps.generate_new_tag.output.release_tag }}
            
     - name: Add new tag
       run:  git tag -a  ${{ steps.generate_new_tag.output.release_tag }} -m "Release tag" 
                    
     - name: Push new tag
       run:  git push origin
