on:
  pull_request:
    branches: [ master ]
    types: [ closed ]
    
    tags-ignore: 
        - '*'
    

jobs:
    pull-request-master-into-release:
     runs-on: ubuntu-latest
     
     #if pull request is merged then only perform the below steps
     if: github.event.pull_request.merged == true

     steps:
       - name: checkout all branches 
         uses: actions/checkout@v2
       
       - name: print environment variables 
         run: |
          echo source: ${{ github.head_ref }}
          echo destination: ${{ github.ref }}
          echo baseRef: ${{ github.base_ref }}  
       
       - name: Get current date
         id: current_date
         run: echo "::set-output name=date::$(date -d "${{ env.TIME_STAMP }} +330 min" +"%d-%b-%Y %H:%M:%S %p")" 

       - name: pull-request (master into release)
         uses: repo-sync/pull-request@v2
         with:
           source_branch: "master"                 
           destination_branch:  "release"                               
           pr_title: "backmerge master into release"             
           pr_body: "This PR is automatically generated by github-actions \n **Creator:** ${{ env.ACTOR }} \n **MERGED_AT:** ${{ steps.current_date.outputs.date }} \n **AUTHOR_EMAIL:** ${{ env.AUTHOR_EMAIL }} \n **AUTHOR_USERNAME:** ${{ env.AUTHOR_USERNAME }} \n **SOURCE_BRANCH:** ${{ env.SOURCE_BRANCH }} \n **TARGET_BRANCH:** ${{ env.TARGET_BRANCH }} \n **ASSIGNEES:** ${{ env.ASSIGNEES }} \n **COMMIT_URL:** ${{ env.URL }}"
           pr_reviewer: "BharatBhushan01"                                         
           pr_assignee: "BharatBhushan01"                  
           pr_label: "Release"                     
           github_token: ${{ secrets.SECRET_TOKEN }}
       
    pull-request-master-into-staging:
     runs-on: ubuntu-latest
     needs: [pull-request-master-into-release]

     steps:
       - name: checkout all branches 
         uses: actions/checkout@v2
       
       - name: Get current date
         id: current_date
         run: echo "::set-output name=date::$(date -d "${{ env.TIME_STAMP }} +330 min" +"%d-%b-%Y %H:%M:%S %p")" 
      
       - name: pull-request (master into staging)
         uses: repo-sync/pull-request@v2
         with:
           source_branch: "master"                 
           destination_branch:  "staging"                               
           pr_title: "backmerge master into staging" 
           pr_body: "This PR is automatically generated by github-actions \n **Creator:** ${{ env.ACTOR }} \n **MERGED_AT:** ${{ steps.current_date.outputs.date }} \n **AUTHOR_EMAIL:** ${{ env.AUTHOR_EMAIL }} \n **AUTHOR_USERNAME:** ${{ env.AUTHOR_USERNAME }} \n **SOURCE_BRANCH:** ${{ env.SOURCE_BRANCH }} \n **TARGET_BRANCH:** ${{ env.TARGET_BRANCH }} \n **ASSIGNEES:** ${{ env.ASSIGNEES }} \n **COMMIT_URL:** ${{ env.URL }}" 
           pr_reviewer: "BharatBhushan01"                                         
           pr_assignee: "BharatBhushan01"                 
           pr_label: "Release"
           github_token: ${{ secrets.SECRET_TOKEN }}
          
     
 # Global environment variables
env:
    CONTEXT: ${{ toJson(github) }}
    ACTOR:  ${{ github.actor }}
    MERGED_AT: ${{ github.event.pull_request.merged_at }}
    SOURCE_BRACNH: ${{ github.head_ref }}
    TARGET_BRANCH: ${{ github.base_ref }}
    AUTHOR_EMAIL: ${{ github.event.commits[0].author.email }}
    AUTHOR_USERNAME: ${{ github.event.commits[0].author.username }}
    ASSIGNEES: $ {{ github.event.pull_request.assignees }}
    URL: ${{ github.event.pull_request._links.html.href }}
        

    run: |
      echo $CONTEXT
      echo $ACTOR
      echo $HEAD_REF
      echo $BASE_REF
      echo $AUTHOR_EMAIL
      echo $COMMIT_MESSAGE
      echo $TIME_STAMP
      echo $URL
