on:
  push:
    branches: [ master ]

jobs:
    pull-request:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v2

       - name: pull-request (master into staging)
         uses: repo-sync/pull-request@v2
         with:
           source_branch: "master"                 
           destination_branch:  "release"                               
           pr_title: "backmerge master into release"             
           pr_body: "This PR is generated automatically by github-actions"              
           pr_reviewer: ""                                          
           pr_assignee: "BharatBhushan01"                  
           pr_label: "auto-pr"                        
           github_token: ${{ secrets.SECRET_TOKEN }}


       - name: pull-request (master into development)
         uses: repo-sync/pull-request@v2
         with:
           source_branch: "master"                 
           destination_branch:  "staging"                               
           pr_title: "backmerge master into staging"
           pr_body: "This PR is generated automatically by github-actions"              
           pr_reviewer: ""                                          
           pr_assignee: "BharatBhushan01"                 
           pr_label: "auto-pr"                        
           github_token: ${{ secrets.SECRET_TOKEN }}

       - name: Dump GitHub context
         env:
             GITHUB_CONTEXT: ${{ toJson(github) }}
             run: echo "$GITHUB_CONTEXT"

       - name: Dump job context
         env:
           JOB_CONTEXT: ${{ toJson(job) }}
           run: echo "$JOB_CONTEXT"
        
