name: Swift

on:
  push:
    branches: [ release ]
    
jobs:
  
  pull-request:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "release"                          # If blank, default: triggered branch
        destination_branch: "master"                      # If blank, default: master
        pr_title: "merge release into master"             # Title of pull request
        pr_body: "This PR is generated automatically by github-actions"                 # Full markdown support, requires pr_title to be set
        pr_reviewer: ""                                   # Comma-separated list (no spaces)
        pr_assignee: "bharatnitp"                         # Comma-separated list (no spaces)
        pr_label: "auto-pr"                               # Comma-separated list (no spaces)
        github_token: ${{ secrets.SECRET_TOKEN }}
    
    
