name: Swift

on:
  pull_request:
    branches: [ development, release ]
    
jobs:
  
  pull-request:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: print environment variables 
      run: |
        echo source: ${{ github.head_ref }}
        echo destination: ${{ github.ref }}
        echo baseRef: ${{ github.base_ref }}  
        
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "release"                          # If blank, default: triggered branch
        destination_branch: "master"                      # If blank, default: master
        pr_title: "merge release into master"             # Title of pull request
        pr_body: "This PR is generated automatically by github-actions"                 # Full markdown support, requires pr_title to be set
        pr_reviewer: ""                                   # Comma-separated list (no spaces)
        pr_assignee: "bharatnitp"                         # Comma-separated list (no spaces)
        pr_label: "auto-pr"                               # Comma-separated list (no spaces)
        github_token: ${{ secrets.SECRET_TOKEN }}
        
        
# Global environment variables
env:
    CONTEXT: ${{ toJson(github) }}
    ACTOR:  ${{ github.actor }}
    HEAD_REF: ${{ github.head_ref }}
    BASE_REF: ${{ github.base_ref }}
    AUTHOR_EMAIL: ${{ github.event.commits[0].author.email }}
    AUTHOR_USERNAME: ${{ github.event.commits[0].author.username }}
    COMMIT_MESSAGE: ${{ github.event.commits[0].message }}
    TIME_STAMP: ${{ github.event.commits[0].timestamp }}
    URL: ${{ github.event.commits[0].url }}
    
    
    
