name: Swift

on:
  push:
    branches: [ master, release, staging, development ]
  pull_request:
    branches: [ master, release, staging, development ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2 
      
    - name: Select xcode 11
      run: sudo xcode-select -switch /Applications/Xcode.app
      
    - name:  Navigate to project dicrectory
      run: cd ..
      
    - name: Build
      run: xcodebuild -scheme FlickerClone build
      
